# These are supported funding model platforms

github: @JoeMark17
patreon: joemarkiewicz
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=VC32NDJFUVQRG&item_name=Hi+There%21+I+am+extremely+grateful+if+you+decide+to+donate+to+my+development+and+charities%2C+otherwise+I+hope+you+enjoy+my+games%21&currency_code=USD
