name: 'dbt_query_game'
version: '0.1.0'
config-version: 2

profile: query

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  +materialized: table

seeds:
  dbt_query_game:
    background_seeds:
      player_data:
        +column_types:
          id: string
      question_vault:
        +column_types:
          model_ref: string
          question: string
          columns_used: string
          query: string
      player_results:
        +column_types:
          date: string
          player_id: string